# Generated by Django 5.1.4 on 2025-01-15 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.hospital'),
            preserve_default=False,
        ),
    ]
