# Generated by Django 5.1.4 on 2025-01-15 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_asset_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithTimeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetCategroy',
            fields=[
                ('modelwithtimestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.modelwithtimestamp')),
                ('name', models.CharField(max_length=200)),
            ],
            bases=('api.modelwithtimestamp',),
        ),
    ]
