# Generated by Django 5.1.4 on 2025-01-15 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_modelwithtimestamp_assetcategroy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='hospital',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.assetcategroy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetcategroy',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.hospital'),
            preserve_default=False,
        ),
    ]
