# Generated by Django 5.1.4 on 2025-01-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_asset_hospital_asset_asset_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetCategroy',
            new_name='AssetCategory',
        ),
    ]
